"""second migration

Revision ID: 8f25c65168d6
Revises: d4f3bec546ad
Create Date: 2019-11-03 09:34:56.124233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f25c65168d6'
down_revision = 'd4f3bec546ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.alter_column('id_vehicle_type',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.alter_column('id_vehicle_type',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
