"""first_migration

Revision ID: d4f3bec546ad
Revises: ffe3d33c8789
Create Date: 2019-11-02 18:34:28.002382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f3bec546ad'
down_revision = 'ffe3d33c8789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_foreign_key('id_vehicle_type', 'vehicletypes', ['id_vehicle_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
