"""added unique constraints

Revision ID: f379f6df5d22
Revises: f794c4d4f9b9
Create Date: 2019-11-05 12:16:41.552736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f379f6df5d22'
down_revision = 'f794c4d4f9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_vehicle_type', 'vehicletypes', ['vehicle_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicletypes', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')
    # ### end Alembic commands ###
